import { Theme } from "Theme.slint";

export component UtilityBadge {
    in property <string> text;
    // info, success, warning, error
    in property <string> status: "info"; 

    height: 20px;

    Rectangle {
        border-radius: Theme.radius_sm;
        
        background: 
            root.status == "success" ? Theme.status_success.transparentize(0.8) :
            root.status == "error" ? Theme.status_error.transparentize(0.8) :
            root.status == "warning" ? Theme.status_warning.transparentize(0.8) :
            Theme.status_info.transparentize(0.8);

        HorizontalLayout {
            padding-left: Theme.space_2;
            padding-right: Theme.space_2;
            
            Text {
                text: root.text;
                font-size: Theme.text_xs;
                font-weight: Theme.font_weight_bold;
                vertical-alignment: center;
                color: 
                    root.status == "success" ? Theme.status_success :
                    root.status == "error" ? Theme.status_error :
                    root.status == "warning" ? Theme.status_warning :
                    Theme.status_info;
            }
        }
    }
}
